---
title: "Demo of testing ETL pipeline using DBT and spark"
date: last-modified
format:
  html:
    output-file: index.html
    toc: true
    toc-depth: 3

    toc-location: left    
    code-fold: true
    number-sections: true       
    other-links:
      - text: github.com project repo
        href: https://github.com/VincentChong123/dbt-spark-demo.git
---

# Introduction
This project is a demo of a dbt workflow for data ingestion, using a finance data ETL pipeline as an example. It emphasizes the importance of performing sanity checks on input data to prevent errors or invalid data from propagating through downstream stages of the data pipeline.

In [ ]:
# import os
# import mermaid as md

# png_path = "../images/diagram.png"
# mermaid_text = """
# graph LR
#     %% Define a CSS class named 'smallText'
#     classDef smallText fontSize:16px;

#     subgraph SQL generation
#         template[Model: YAML, SQL] ----> DBT(docker: custom-dbt)
#     end

#     DBT -- SQL --> SparkThrift
#     SparkThrift -- Data --> DBT

#     subgraph SQL-processing & db
#         SparkThrift(docker: dbt-spark3-thrift) -- Queries --> PostgreSQL_Hive_Metastore(docker: dbt-hive-metastore)
#         PostgreSQL_Hive_Metastore -- Data --> SparkThrift
#     end

#     style DBT fill:#f9f,stroke:#333,stroke-width:2px
#     style SparkThrift fill:#ccf,stroke:#333,stroke-width:2px
#     style PostgreSQL_Hive_Metastore fill:#cff,stroke:#333,stroke-width:2px
# """
# md.Mermaid(mermaid_text).to_png(path=png_path)
# assert os.path.exists(png_path)

# DBT demo block diagram
![DBT demo block diagram](../images/diagram.png)

In [ ]:
import pandas as pd

pd.read_csv("/usr/app/demo/dbt_spark_demo_prj/seeds/transactions/raw__transactions.csv")

## Project file structure

In [ ]:
!tree -L 2 --sort="name" /usr/app | grep -v ".*\.toml$" | grep -v ".*\.md$" | grep -v ".*files$"

# Environment setup

## Docker
### Shared network for docker containers
```bash
docker network create --attachable my_shared_network
```

## Install jupyter notebook for running this demo in notebook 
This notebook is executed using jupyer-notebook kernel (http://127.0.0.1:8888) of the loaded custom-dbt container. The container is loaded using command below
```bash
jupyter notebook --NotebookApp.token='' --NotebookApp.password='' --NotebookApp.disable_check_xsrf=True --allow-root --ip=0.0.0.0 --port=8888 --no-browser
```
use allow-root for demo purpose only, not for production due to cyber security

In [ ]:
%%bash
export TZ='Asia/Singapore'
date
which python
pwd

## Variables in dbt docker container

In [16]:
from dotenv import load_dotenv
import os
!pwd

load_dotenv()
spark_thrift_service_name=os.getenv('SPARK_CONTAINER_SERVICE_NAME')
dbt_project_dir=os.getenv('DBT_PROJECT_DIR')
dbt_project_name=os.getenv('DBT_PROJECT_NAME')
print("spark_thrift_service_name: ", spark_thrift_service_name)
print("dbt_project_dir:", dbt_project_dir)
print("dbt_project_name: ",dbt_project_name)

/usr/app/demo
spark_thrift_service_name:  dbt-spark3-thrift
dbt_project_dir: /usr/app/dbt/dbt_spark_demo_prj
dbt_project_name:  dbt_spark_demo_prj

# Start demo

In [ ]:
filepath="/usr/app/demo/results/test_start.txt"
!echo start test at > $filepath 
!export TZ='Asia/Singapore'; date >> $filepath

## Helper codes

In [17]:
from pyhive import hive
import pandas as pd
from sqlalchemy.engine import create_engine
from typing import List


def show_databases(
    host="dbt-spark3-thrift", message_to_be_printed="", port=10000
) -> List[str]:
    # with hive.Connection(host=spark_thrift_service_name, port=10000,
    #                     #    username='',
    #                     database='default') as conn:

    #     # Query all tables in the default database
    #     df = pd.read_sql("SHOW TABLES", conn)

    #     # Display tables
    #     display(df)
    print(message_to_be_printed)
    engine = create_engine(f"hive://{host}:{port}/")
    df = pd.read_sql("SHOW DATABASES;", engine)
    display(df)
    return df.namespace.to_list()


def show_tables(
    host="dbt-spark3-thrift", database_name="default", message_to_be_printed=""
) -> List[str]:
    # with hive.Connection(host=spark_thrift_service_name, port=10000,
    #                     #    username='',
    #                     database='default') as conn:

    #     # Query all tables in the default database
    #     df = pd.read_sql("SHOW TABLES", conn)

    #     # Display tables
    #     display(df)
    print(message_to_be_printed)
    engine = create_engine(f"hive://{host}:10000/{database_name}")
    df = pd.read_sql("SHOW TABLES;", engine)
    display(df)
    return df.tableName.to_list()


def select_from_table(
    database_name="default",
    table_name="transactions",
    host="dbt-spark3-thrift",
    port=10000,
    message_to_be_printed="",
    suffix_sql="",
):
    # sqlAlchemy api fail here due to "sqlAlchemy relection": TODO investigate root cause
    # engine = create_engine(f'hive://{spark_thrift_service_name}:10000/default')
    # df = pd.read_sql(f"select * from {table_name} limit 10", engine)

    print(message_to_be_printed)
    with hive.Connection(host=host, port=port, database=database_name) as conn:
        df = pd.read_sql(
            f"select * from {database_name}.{table_name} {suffix_sql};", conn
        )
        display(df)
        pass


# print(show_databases(message_to_be_printed="tables in database"))

table_names = show_tables(database_name="default", message_to_be_printed=f"{'='*10}")
# print("------------")
# select_from_table()
for names in table_names:
    select_from_table(
        table_name="raw__transactions", message_to_be_printed=f"{'-'*10}{names}"
    )

==========

  namespace          tableName  isTemporary
0   default  raw__transactions        False
1   default       transactions        False

----------raw__transactions

/tmp/ipykernel_98/3788726696.py:59: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(

   id   amount currency    status
0   5  180.040      SGD  INACTIVE
1   7  300.123      SUD    ACTIVE
2   1  100.000      USD    ACTIVE
3   4  120.030      USD  INACTIVE
4   6 -300.050      JPY    ACTIVE
5   3  150.020      EUR    ACTIVE
6   2  200.010      SGD    ACTIVE

----------transactions

/tmp/ipykernel_98/3788726696.py:59: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(

   id   amount currency    status
0   5  180.040      SGD  INACTIVE
1   7  300.123      SUD    ACTIVE
2   1  100.000      USD    ACTIVE
3   4  120.030      USD  INACTIVE
4   6 -300.050      JPY    ACTIVE
5   3  150.020      EUR    ACTIVE
6   2  200.010      SGD    ACTIVE

## DBT

In [18]:
!dbt --version

Core:
  - installed: 1.10.2
  - latest:    1.10.4 - Update available!

  Your version of dbt-core is out of date!
  You can find instructions for upgrading here:
  https://docs.getdbt.com/docs/installation

Plugins:
  - spark: 1.9.2 - Up to date!

## Verify DBT setup

### profiles.yml
```yml
formal_verification_prj_name:
  outputs:
    spark:
      type: spark
      method: thrift
      host: dbt-spark3-thrift
      schema: default
      connect_timeout: 30
      authentication: NONE
  target: spark

```

In [20]:
!cat $dbt_project_dir/dbt_project.yml | grep -v "#"

name: 'dbt_spark_demo_prj'
version: '1.0.0'

profile: 'dbt_spark_demo_prj'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

  - "target"
  - "dbt_packages"



models:
  dbt_spark_demo_prj:
    +materialized: incremental
    +file_format: parquet

tests:

### Verify dbt environment (dbt debug)

In [21]:
!dbt debug --project-dir $dbt_project_dir;

#to print detailed messages for debugging 
#!dbt debug --debug --project-dir /usr/app/dbt/dbt_spark_demo_prj

06:53:27  Running with dbt=1.10.2
06:53:27  dbt version: 1.10.2
06:53:27  python version: 3.11.2
06:53:27  python path: /usr/local/bin/python3
06:53:27  os info: Linux-5.15.167.4-microsoft-standard-WSL2-x86_64-with-glibc2.31
06:53:27  Using profiles dir at /usr/app/demo
06:53:27  Using profiles.yml file at /usr/app/demo/profiles.yml
06:53:27  Using dbt_project.yml file at /usr/app/dbt/dbt_spark_demo_prj/dbt_project.yml
06:53:27  adapter type: spark
06:53:27  adapter version: 1.9.2
06:53:28  Configuration:
06:53:28    profiles.yml file [OK found and valid]
06:53:28    dbt_project.yml file [OK found and valid]
06:53:28  Required dependencies:
06:53:28   - git [OK found]

06:53:28  Connection:
06:53:28    host: dbt-spark3-thrift
06:53:28    port: 10000
06:53:28    cluster: None
06:53:28    endpoint: None
06:53:28    schema: default
06:53:28    organization: 0
06:53:28  Registered adapter: spark=1.9.2
06:53:28    Connection test: [OK connection ok]

06:53:28  All checks passed!

## dbt command comparisons
| Command           | Purpose                                  | What it does                                                             | Output                                    |
| ----------------- | ---------------------------------------- | ------------------------------------------------------------------------ | ----------------------------------------- |
| **`dbt compile`** | Prepares SQL code for execution          | Converts Jinja + macros into raw SQL; writes compiled files to `target/` | Compiled SQL files (no warehouse changes) |
| **`dbt run`**     | Builds models (tables/views)             | Executes compiled SQL to materialize models in the data warehouse        | Tables/views in the warehouse             |
| **`dbt test`**    | Validates data quality assumptions       | Runs data tests (e.g., `not_null`, `unique`, custom) on warehouse data   | Test pass/fail results                    |
| **`dbt seed`**    | Loads static CSV data into the warehouse | Uploads CSV files from the `seeds/` directory into tables                 | Tables containing seed data               |

# Delete database table

In [22]:
db_names = show_databases()
print(db_names)
for d in db_names:
    if d != 'default':
        arg = "'{" + '"database_name"' + ": " + f'"{d}"' + "}'"
        print(f"arg {arg}")
        !dbt run-operation drop_database --args $arg  
database_names = show_databases();

table_names = show_tables(database_name="default",  message_to_be_printed="Tables in default database before deleting table");
for t in table_names:
    print(t)
    arg = "'{" + '"table_name"' + ":" + f'"default.{t}"' + "}'"
    !dbt run-operation drop_table --args $arg  
table_names = show_tables(database_name="default", message_to_be_printed="Tables in default database after deleting table");

                 namespace
0                  default
1  default_dbt_test__audit

['default', 'default_dbt_test__audit']
arg '{"database_name": "default_dbt_test__audit"}'
06:53:54  Running with dbt=1.10.2
06:53:55  Registered adapter: spark=1.9.2
06:53:55  Unable to do partial parsing because saved manifest not found. Starting full parse.
06:53:58  Warning: No columns found for model all_columns_non_null_transactions_. Skipping non-null check.
06:53:58  Warning: No columns found for model all_columns_non_null_raw__transactions_. Skipping non-null check.
06:53:59  Found 1 model, 1 seed, 8 data tests, 480 macros, 3 unit tests

  namespace
0   default

Tables in default database before deleting table

  namespace          tableName  isTemporary
0   default  raw__transactions        False
1   default       transactions        False

raw__transactions
06:54:08  Running with dbt=1.10.2
06:54:10  Registered adapter: spark=1.9.2
06:54:12  Found 1 model, 1 seed, 8 data tests, 480 macros, 3 unit tests
transactions
06:54:19  Running with dbt=1.10.2
06:54:19  Registered adapter: spark=1.9.2
06:54:20  Found 1 model, 1 seed, 8 data tests, 480 macros, 3 unit tests
Tables in default database after deleting table

Empty DataFrame
Columns: [namespace, tableName, isTemporary]
Index: []

# Generate SQL for models and seeds

## Read input csv 

* read seeds/transactions.csv, 
* dbt generate raw__transaction.csv
* dbt create table default.raw_transaction at the database

In [23]:
!dbt seed --project-dir $dbt_project_dir;
show_databases(message_to_be_printed="\nDatabase table after the operation")
show_tables(message_to_be_printed="\nTable after the dbt seed")
select_from_table(
    database_name="default", table_name="raw__transactions", suffix_sql="order by id"
)

06:59:07  Running with dbt=1.10.2
06:59:07  Registered adapter: spark=1.9.2
06:59:08  Found 1 model, 1 seed, 8 data tests, 480 macros, 3 unit tests
06:59:08
06:59:08  Concurrency: 1 threads (target='spark')
06:59:08
06:59:08  1 of 1 START seed file default.raw__transactions ............................... [RUN]
06:59:09  1 of 1 OK loaded seed file default.raw__transactions ........................... [INSERT 7 in 1.15s]
06:59:09
06:59:09  Finished running 1 seed in 0 hours 0 minutes and 1.62 seconds (1.62s).
06:59:10
06:59:10  Completed successfully
06:59:10
06:59:10  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 NO-OP=0 TOTAL=1

Database table after the operation

  namespace
0   default

Table after the dbt seed

  namespace          tableName  isTemporary
0   default  raw__transactions        False

/tmp/ipykernel_98/3788726696.py:59: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(

   id   amount currency    status
0   1  100.000      USD    ACTIVE
1   2  200.010      SGD    ACTIVE
2   3  150.020      EUR    ACTIVE
3   4  120.030      USD  INACTIVE
4   5  180.040      SGD  INACTIVE
5   6 -300.050      JPY    ACTIVE
6   7  300.123      SUD    ACTIVE

# Generate SQL (dbt compile)

In [24]:
!rm -rf $dbt_project_dir/target/compiled/
!dbt compile --project-dir $dbt_project_dir --log-level info;

# Start: temporary solution "dbt compile" error of missing table *_audit"
!dbt run --log-level info --project-dir $dbt_project_dir;
!dbt test --log-level info --project-dir $dbt_project_dir;
# end

!dbt compile --project-dir $dbt_project_dir --log-level info;

# !export TZ='Asia/Singapore'; date; ls -lrt dbt/dbt_spark_demo_prj/target/compiled/

06:59:23  Running with dbt=1.10.2
06:59:23  Registered adapter: spark=1.9.2
06:59:24  Found 1 model, 1 seed, 8 data tests, 480 macros, 3 unit tests
06:59:24
06:59:24  Concurrency: 1 threads (target='spark')
06:59:24
06:59:25  Warning: No columns found for model transactions. Skipping non-null check.
06:59:30  Running with dbt=1.10.2
06:59:31  Registered adapter: spark=1.9.2
06:59:31  Found 1 model, 1 seed, 8 data tests, 480 macros, 3 unit tests
06:59:31
06:59:31  Concurrency: 1 threads (target='spark')
06:59:31
06:59:32  1 of 1 START sql table model default.transactions .............................. [RUN]
06:59:33  1 of 1 OK created sql table model default.transactions ......................... [OK in 0.72s]
06:59:33
06:59:33  Finished running 1 table model in 0 hours 0 minutes and 1.16 seconds (1.16s).
06:59:33
06:59:33  Completed successfully
06:59:33
06:59:33  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 NO-OP=0 TOTAL=1
06:59:38  Running with dbt=1.10.2
06:59:38  Registered adapter: spark=1.9.2
06:59:39  Found 1 model, 1 seed, 8 data tests, 480 macros, 3 unit tests
06:59:39
06:59:39  Concurrency: 1 threads (target='spark')
06:59:39
06:59:39  1 of 11 START test accepted_values_transactions_branch_marker__USD_BRANCH__SGD_BRANCH__UNKNOWN_BRANCH  [RUN]
06:59:40  1 of 11 PASS accepted_values_transactions_branch_marker__USD_BRANCH__SGD_BRANCH__UNKNOWN_BRANCH  [PASS in 0.91s]
06:59:40  2 of 11 START test accepted_values_transactions_currency__USD__SGD ............. [RUN]
06:59:41  2 of 11 FAIL 3 accepted_values_transactions_currency__USD__SGD ................. [FAIL 3 in 1.05s]
06:59:41  3 of 11 START test all_columns_non_null_raw__transactions_ ..................... [RUN]
06:59:43  3 of 11 PASS all_columns_non_null_raw__transactions_ ........................... [PASS in 1.28s]
06:59:43  4 of 11 START test all_columns_non_null_transactions_ .......................... [RUN]
06:59:44  4 of 11 FAIL 3 all_columns_non_null_transactions_ .............................. [FAIL 3 in 1.21s]
06:59:44  5 of 11 START test not_null_transactions_branch_marker ......................... [RUN]
06:59:45  5 of 11 PASS not_null_transactions_branch_marker ............................... [PASS in 0.75s]
06:59:45  6 of 11 START test not_null_transactions_currency .............................. [RUN]
06:59:46  6 of 11 PASS not_null_transactions_currency .................................... [PASS in 1.03s]
06:59:46  7 of 11 START test not_null_transactions_id .................................... [RUN]
06:59:47  7 of 11 PASS not_null_transactions_id .......................................... [PASS in 0.91s]
06:59:47  8 of 11 START test unique_transactions_id ...................................... [RUN]
06:59:47  8 of 11 PASS unique_transactions_id ............................................ [PASS in 0.91s]
06:59:47  9 of 11 START unit_test transactions::test_currency_sgd ........................ [RUN]
06:59:48  9 of 11 FAIL 1 transactions::test_currency_sgd ................................. [FAIL 1 in 0.52s]
06:59:48  10 of 11 START unit_test transactions::test_currency_usd ....................... [RUN]
06:59:48  10 of 11 PASS transactions::test_currency_usd .................................. [PASS in 0.46s]
06:59:48  11 of 11 START unit_test transactions::test_inactive ........................... [RUN]
06:59:49  11 of 11 PASS transactions::test_inactive ...................................... [PASS in 0.41s]
06:59:49
06:59:49  Finished running 8 data tests, 3 unit tests in 0 hours 0 minutes and 10.11 seconds (10.11s).
06:59:49
06:59:49  Completed with 3 errors, 0 partial successes, and 0 warnings:
06:59:49
06:59:49  Failure in test accepted_values_transactions_currency__USD__SGD (models/transactions/transactions.yml)
06:59:49    Got 3 results, configured to fail if != 0
06:59:49
06:59:49    compiled code at target/compiled/dbt_spark_demo_prj/models/transactions/transactions.yml/accepted_values_transactions_currency__USD__SGD.sql
06:59:49
06:59:49    See test failures:
  -------------------------------------------------------------------------------------
  select * from default_dbt_test__audit.accepted_values_transactions_currency__USD__SGD
  -------------------------------------------------------------------------------------
06:59:49
06:59:49  Failure in test all_columns_non_null_transactions_ (models/transactions/transactions.yml)
06:59:49    Got 3 results, configured to fail if != 0
06:59:49
06:59:49    compiled code at target/compiled/dbt_spark_demo_prj/models/transactions/transactions.yml/all_columns_non_null_transactions_.sql
06:59:49
06:59:49    See test failures:
  ------------------------------------------------------------------------
  select * from default_dbt_test__audit.all_columns_non_null_transactions_
  ------------------------------------------------------------------------
06:59:49
06:59:49  Failure in unit_test test_currency_sgd (tests/unit/test_transactions.yml)
06:59:49

actual differs from expected:

@@,id,amount_usd,branch_marker
→ ,2 ,74.0→NULL ,SGD_BRANCH→UNKNOWN_BRANCH


06:59:49
06:59:49    compiled code at target/compiled/dbt_spark_demo_prj/tests/unit/test_transactions.yml/tests/unit/test_currency_sgd.sql
06:59:49
06:59:49  Done. PASS=8 WARN=0 ERROR=3 SKIP=0 NO-OP=0 TOTAL=11
06:59:56  Running with dbt=1.10.2
06:59:57  Registered adapter: spark=1.9.2
06:59:58  Found 1 model, 1 seed, 8 data tests, 480 macros, 3 unit tests
06:59:58
06:59:58  Concurrency: 1 threads (target='spark')
06:59:58

## Create tables using the generated SQL (dbt run)

In [ ]:
# Delete database table prior dbt run that will create the table
!rm -r $dbt_project_dir/target/run
!dbt run-operation drop_table --args '{"table_name": "default.transactions"}' 

show_tables(database_name='default', message_to_be_printed="before")
!dbt run --log-level info --project-dir $dbt_project_dir;

# Check output dbt run
show_tables(database_name='default', message_to_be_printed="after")
select_from_table(database_name='default', table_name='transactions')

## Test model (dbt test)
#### test case name and its test vectors

In [25]:
!tree $dbt_project_dir/tests
!cat $dbt_project_dir/models/transactions/transactions.yml | grep -v "#"

/usr/app/dbt/dbt_spark_demo_prj/tests
├── schema
└── unit
    └── test_transactions.yml

2 directories, 1 file
version: 2

models:
    description: "This model processes raw transaction data, filters for active transactions, and standardizes amounts to USD while also assigning a branch marker based on the transaction currency."
    tests:
      - all_columns_non_null: {}
    columns:
      - name: id
        description: "The unique identifier for each transaction."
        tests:
          - unique
          - not_null
      - name: amount
        description: "The original transaction amount in its respective currency."
      - name: currency
        description: "The original currency of the transaction (e.g., 'USD', 'SGD')."
        tests:
          - not_null
          - accepted_values:
      - name: amount_usd
        description: "The transaction amount converted to US Dollars. SGD amounts are converted using a fixed rate (0.74), while USD amounts remain unchanged."
      - name: branch_marker
        description: "A categorical marker indicating the likely branch based on the transaction currency ('USD_BRANCH', 'SGD_BRANCH', or 'UNKNOWN_BRANCH')."
        tests:
          - not_null
          - accepted_values:
              values: ['USD_BRANCH', 'SGD_BRANCH', 'UNKNOWN_BRANCH']

In [26]:
# %%bash
# export DBT_PROJECT_DIR=$dbt_project_dir
show_databases(message_to_be_printed="Before run test")
!dbt test --store-failures --project-dir $dbt_project_dir --log-level info;

Before run test

                 namespace
0                  default
1  default_dbt_test__audit

07:03:03  Running with dbt=1.10.2
07:03:04  Registered adapter: spark=1.9.2
07:03:05  Found 1 model, 1 seed, 8 data tests, 480 macros, 3 unit tests
07:03:05
07:03:05  Concurrency: 1 threads (target='spark')
07:03:05
07:03:05  1 of 11 START test accepted_values_transactions_branch_marker__USD_BRANCH__SGD_BRANCH__UNKNOWN_BRANCH  [RUN]
07:03:07  1 of 11 PASS accepted_values_transactions_branch_marker__USD_BRANCH__SGD_BRANCH__UNKNOWN_BRANCH  [PASS in 1.62s]
07:03:07  2 of 11 START test accepted_values_transactions_currency__USD__SGD ............. [RUN]
07:03:08  2 of 11 FAIL 3 accepted_values_transactions_currency__USD__SGD ................. [FAIL 3 in 1.44s]
07:03:08  3 of 11 START test all_columns_non_null_raw__transactions_ ..................... [RUN]
07:03:10  3 of 11 PASS all_columns_non_null_raw__transactions_ ........................... [PASS in 1.36s]
07:03:10  4 of 11 START test all_columns_non_null_transactions_ .......................... [RUN]
07:03:11  4 of 11 FAIL 3 all_columns_non_null_transactions_ .............................. [FAIL 3 in 1.55s]
07:03:11  5 of 11 START test not_null_transactions_branch_marker ......................... [RUN]
07:03:12  5 of 11 PASS not_null_transactions_branch_marker ............................... [PASS in 1.15s]
07:03:12  6 of 11 START test not_null_transactions_currency .............................. [RUN]
07:03:14  6 of 11 PASS not_null_transactions_currency .................................... [PASS in 1.60s]
07:03:14  7 of 11 START test not_null_transactions_id .................................... [RUN]
07:03:16  7 of 11 PASS not_null_transactions_id .......................................... [PASS in 1.56s]
07:03:16  8 of 11 START test unique_transactions_id ...................................... [RUN]
07:03:17  8 of 11 PASS unique_transactions_id ............................................ [PASS in 1.84s]
07:03:17  9 of 11 START unit_test transactions::test_currency_sgd ........................ [RUN]
07:03:18  9 of 11 FAIL 1 transactions::test_currency_sgd ................................. [FAIL 1 in 0.93s]
07:03:18  10 of 11 START unit_test transactions::test_currency_usd ....................... [RUN]
07:03:19  10 of 11 PASS transactions::test_currency_usd .................................. [PASS in 0.53s]
07:03:19  11 of 11 START unit_test transactions::test_inactive ........................... [RUN]
07:03:20  11 of 11 PASS transactions::test_inactive ...................................... [PASS in 0.93s]
07:03:20
07:03:20  Finished running 8 data tests, 3 unit tests in 0 hours 0 minutes and 15.44 seconds (15.44s).
07:03:20
07:03:20  Completed with 3 errors, 0 partial successes, and 0 warnings:
07:03:20
07:03:20  Failure in test accepted_values_transactions_currency__USD__SGD (models/transactions/transactions.yml)
07:03:20    Got 3 results, configured to fail if != 0
07:03:20
07:03:20    compiled code at target/compiled/dbt_spark_demo_prj/models/transactions/transactions.yml/accepted_values_transactions_currency__USD__SGD.sql
07:03:20
07:03:20    See test failures:
  -------------------------------------------------------------------------------------
  select * from default_dbt_test__audit.accepted_values_transactions_currency__USD__SGD
  -------------------------------------------------------------------------------------
07:03:20
07:03:20  Failure in test all_columns_non_null_transactions_ (models/transactions/transactions.yml)
07:03:20    Got 3 results, configured to fail if != 0
07:03:20
07:03:20    compiled code at target/compiled/dbt_spark_demo_prj/models/transactions/transactions.yml/all_columns_non_null_transactions_.sql
07:03:20
07:03:20    See test failures:
  ------------------------------------------------------------------------
  select * from default_dbt_test__audit.all_columns_non_null_transactions_
  ------------------------------------------------------------------------
07:03:20
07:03:20  Failure in unit_test test_currency_sgd (tests/unit/test_transactions.yml)
07:03:20

actual differs from expected:

@@,id,amount_usd,branch_marker
→ ,2 ,74.0→NULL ,SGD_BRANCH→UNKNOWN_BRANCH


07:03:20
07:03:20    compiled code at target/compiled/dbt_spark_demo_prj/tests/unit/test_transactions.yml/tests/unit/test_currency_sgd.sql
07:03:20
07:03:20  Done. PASS=8 WARN=0 ERROR=3 SKIP=0 NO-OP=0 TOTAL=11

In [ ]:
database_names = show_databases(message_to_be_printed="After run test")
for d in database_names:
    if d != "default" and "audit" in d:
        table_names = show_tables(
            message_to_be_printed=f"database_name: {d}", database_name=d
        )
        for t in table_names:
            select_from_table(
                table_name=t,
                database_name=d,
                message_to_be_printed=f"\t\ttable_name: {t}",
            )

In [ ]:
!chmod -R a+rw /usr/app

In [ ]:
filepath="/usr/app/demo/results/test_end.txt"
!date; echo end test at > $filepath 
!export TZ='Asia/Singapore'; date >> $filepath;

## API documentation
### Generate dbt documentation

In [27]:
!cd $dbt_project_dir; dbt docs generate;

07:03:31  Running with dbt=1.10.2
07:03:32  Registered adapter: spark=1.9.2
07:03:34  Found 1 model, 1 seed, 8 data tests, 480 macros, 3 unit tests
07:03:34
07:03:34  Concurrency: 1 threads (target='spark')
07:03:34
07:03:36  Building catalog
07:03:37  Catalog written to /usr/app/dbt/dbt_spark_demo_prj/target/catalog.json

### Serve generated documentation

at docker host, run command 
```bash
cd dbt-spark-demo/dbt/dbt_spark_demo_prj/target/
python -m http.server 8060
```
at web broswer, open http://localhost:8060/#!/model/

Sample API documentation
![API documentation](../docs/images/api-documentation.png)

In [ ]:
# assert False, "Stop execution here!"

# Apendix

## check the model built

### Check the model built using Pyspark (In progress)

In [ ]:
# !pip install pyspark==3.3.2

In [ ]:
# %%bash
# # For Debian/Ubuntu-based containers:
# apt-get update && apt-get install -y openjdk-11-jdk

# # For Alpine-based containers:
# apk add openjdk11

In [ ]:
# !ls /usr/lib/jvm/java-11-openjdk-amd64

In [ ]:
# # !. /usr/spark/bin/load-spark-env.sh

# # Typically in Debian/Ubuntu:
# !export JAVA_HOME=$(dirname $(dirname $(readlink -f $(which java))))

# # Or set it explicitly:
# !export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
# from pyspark.sql import SparkSession

# spark = SparkSession.builder \
#     .appName("dbt_clean") \
#     .config("spark.hadoop.hive.metastore.schema.verification", "true") \
#     .config("spark.sql.catalogImplementation", "hive") \
#     .enableHiveSupport() \
#     .getOrCreate()

# # spark = SparkSession.builder \
# #     .config("hive.metastore.uris", "thrift://dbt-hive-metastore:10000") \
# #     .config("spark.sql.catalogImplementation", "hive") \
# #     .enableHiveSupport() \
# #     .getOrCreate()

# spark.sql("USE default")  # Or your specific database
# spark.sql("SHOW DATABASES").show()
# # spark.sql("select * from transactions").show()
# # # df.toPandas()

In [ ]:
# spark.sql("SHOW TABLES IN default").show(truncate=False)

In [ ]:
# # Query metastore system tables
# spark.sql("""
#   SELECT TBL_NAME, TBL_TYPE
#   FROM default.TBLS
#   JOIN default.DBS ON TBLS.DB_ID = DBS.DB_ID
#   WHERE DBS.NAME = 'default'
# """).show(truncate=False)

In [ ]:
# spark.conf.get("hive.metastore.uris")  # Should return your URI

In [ ]:
# spark.conf.get("spark.sql.catalogImplementation")  # Should return "hive"

In [ ]:
# from pyspark.sql import SparkSession

# spark.stop()
# spark = SparkSession.builder \
#     .appName("DBTIntegration") \
#     .config("hive.metastore.uris", "thrift://dbt-hive-metastore:9083") \
#     .config("spark.sql.catalogImplementation", "hive") \
#     .config("javax.jdo.option.ConnectionUserName", "dbt") \
#     .config("javax.jdo.option.ConnectionPassword", "dbt") \
#     .enableHiveSupport() \
#     .getOrCreate()
# spark.sql("SHOW TABLES IN default")

In [ ]:
# from pyhive import hive
# conn = hive.connect(host=spark_thrift_service_name, port=10000)
# cursor = conn.cursor()
# cursor.execute("SELECT * FROM default.transactions LIMIT 1")
# print(cursor.fetchall())

### Test the built model (using the test model) 
### dbt test

In [ ]:
# !dbt test --log-level info

In [ ]:
# !cat /home/vin/01-prj/stripe/sql-formal-verification/formal_verification_prj_name/tests/unit/test_transactions.yml

In [ ]:
# %%bash
# cd /usr/app/dbt
# dbt compile --profiles-dir /usr/app/dbt  --project-dir /usr/app/dbt/dbt_spark_demo_prj
# # dbt run-operation drop_table --args '{"table_name": "default.transactions"}'
# dbt run-operation drop_view --args '{"view_name": "default.my_first_dbt_model"}' --profiles-dir /usr/app/dbt  --project-dir /usr/app/dbt/dbt_spark_demo_prj
# dbt run-operation drop_view --args '{"view_name": "default.my_second_dbt_model"}' --profiles-dir /usr/app/dbt  --project-dir /usr/app/dbt/dbt_spark_demo_prj

<!-- # Todo
## Audit compliance 
### time tracing with time-stamping
1. Add timestamp for loaded data using dbt model
```jinja
SELECT
    *,
    '{{ run_started_at }}'::timestamp AS added_at
FROM {{ ref('my_seed_table') }}
```
### File tracing with source and targets file path, tablename -->

# End of notebook