---
title: "Demo of testing ETL pipeline using DBT and spark"
date: last-modified
format:
  html:
    output-file: index.html
    toc: true
    toc-depth: 3

    toc-location: left    
    code-fold: true
    number-sections: true       
    other-links:
      - text: github.com project repo
        href: https://github.com/VincentChong123/dbt-spark-demo.git
---

# Introduction
This project is a demo of a dbt workflow for data ingestion, using a finance data ETL pipeline as an example. It emphasizes the importance of performing sanity checks on input data to prevent errors or invalid data from propagating through downstream stages of the data pipeline.

In [ ]:
# import os
# import mermaid as md

# png_path = "../images/diagram.png"
# mermaid_text = """
# graph LR
#     %% Define a CSS class named 'smallText'
#     classDef smallText fontSize:16px;

#     subgraph SQL generation
#         template[Model: YAML, SQL] ----> DBT(docker: custom-dbt)
#     end

#     DBT -- SQL --> SparkThrift
#     SparkThrift -- Data --> DBT

#     subgraph SQL-processing & db
#         SparkThrift(docker: dbt-spark3-thrift) -- Queries --> PostgreSQL_Hive_Metastore(docker: dbt-hive-metastore)
#         PostgreSQL_Hive_Metastore -- Data --> SparkThrift
#     end

#     style DBT fill:#f9f,stroke:#333,stroke-width:2px
#     style SparkThrift fill:#ccf,stroke:#333,stroke-width:2px
#     style PostgreSQL_Hive_Metastore fill:#cff,stroke:#333,stroke-width:2px
# """
# md.Mermaid(mermaid_text).to_png(path=png_path)
# assert os.path.exists(png_path)

# DBT demo block diagram
![DBT demo block diagram](../images/diagram.png)

In [ ]:
import pandas as pd

pd.read_csv("/usr/app/demo/dbt_spark_demo_prj/seeds/transactions/raw__transactions.csv")

   id   amount currency    status
0   1  100.000      USD    ACTIVE
1   2  200.010      SGD    ACTIVE
2   3  150.020      EUR    ACTIVE
3   4  120.030      USD  INACTIVE
4   5  180.040      SGD  INACTIVE
5   6 -300.050      JPY    ACTIVE
6   7  300.123      SUD    ACTIVE

## Project file structure

In [278]:
!tree -L 2 --sort="name" /usr/app | grep -v ".*\.toml$" | grep -v ".*\.md$" | grep -v ".*files$"

25484.46s - pydevd: Sending message related to process being replaced timed-out after 5 seconds

/usr/app
├── dbt
│   ├── dbt.Dockerfile
│   ├── dbt_spark_demo_prj
│   ├── docker-compose.yml
│   ├── logs
│   └── requirements.txt
├── dbt-spark
│   ├── dagger
│   ├── dbt
│   ├── docker
│   ├── docker-compose.yml
│   ├── scripts
│   ├── test.env.example
│   └── tests
├── dbt-spark-demo.html:Zone.Identifier
├── dbt-spark-demo_files
│   └── libs
├── demo
│   ├── dbt-spark-demo.ipynb
│   ├── dbt-spark-demo_files
│   ├── dbt_spark_demo_prj
│   ├── generate-documentation.sh
│   ├── index.html
│   ├── profiles.yml
│   └── results
├── docs
│   ├── dbt-spark-demo_files
│   ├── index.html
│   └── index.html:Zone.Identifier
├── images
│   └── diagram.png
├── index.html
├── index.html:Zone.Identifier
├── logs
│   └── dbt.log
└── run-demo.sh

# Environment setup

## Docker
### Shared network for docker containers
```bash
docker network create --attachable my_shared_network
```

## Install jupyter notebook for running this demo in notebook 
This notebook is executed using jupyer-notebook kernel (http://127.0.0.1:8888) of the loaded custom-dbt container. The container is loaded using command below
```bash
jupyter notebook --NotebookApp.token='' --NotebookApp.password='' --NotebookApp.disable_check_xsrf=True --allow-root --ip=0.0.0.0 --port=8888 --no-browser
```
use allow-root for demo purpose only, not for production due to cyber security

In [1]:
%%bash
export TZ='Asia/Singapore'
date
which python
pwd

Mon Jul 14 08:52:56 +08 2025
/usr/local/bin/python
/usr/app

### Connection to read table in Hive meta-data store

## Variables

In [5]:
from dotenv import load_dotenv
import os
!pwd

load_dotenv()
spark_thrift_service_name=os.getenv('SPARK_CONTAINER_SERVICE_NAME')
dbt_project_dir=os.getenv('DBT_PROJECT_DIR')
dbt_project_name=os.getenv('DBT_PROJECT_NAME')
print("spark_thrift_service_name: ", spark_thrift_service_name)
print("dbt_project_dir:", dbt_project_dir)
print("dbt_project_name: ",dbt_project_name)

/usr/app
spark_thrift_service_name:  dbt-spark3-thrift
dbt_project_dir: /usr/app/dbt/dbt_spark_demo_prj
dbt_project_name:  dbt_spark_demo_prj

# Start demo

In [3]:
filepath="/usr/app/demo/results/test_start.txt"
!echo start test at > $filepath 
!export TZ='Asia/Singapore'; date >> $filepath

## Helper codes

In [9]:
from pyhive import hive
import pandas as pd
from sqlalchemy.engine import create_engine
from typing import List


def show_databases(
    host="dbt-spark3-thrift", message_to_be_printed="", port=10000
) -> List[str]:
    # with hive.Connection(host=spark_thrift_service_name, port=10000,
    #                     #    username='',
    #                     database='default') as conn:

    #     # Query all tables in the default database
    #     df = pd.read_sql("SHOW TABLES", conn)

    #     # Display tables
    #     display(df)
    print(message_to_be_printed)
    engine = create_engine(f"hive://{host}:{port}/")
    df = pd.read_sql("SHOW DATABASES;", engine)
    display(df)
    return df.namespace.to_list()


def show_tables(
    host="dbt-spark3-thrift", database_name="default", message_to_be_printed=""
) -> List[str]:
    # with hive.Connection(host=spark_thrift_service_name, port=10000,
    #                     #    username='',
    #                     database='default') as conn:

    #     # Query all tables in the default database
    #     df = pd.read_sql("SHOW TABLES", conn)

    #     # Display tables
    #     display(df)
    print(message_to_be_printed)
    engine = create_engine(f"hive://{host}:10000/{database_name}")
    df = pd.read_sql("SHOW TABLES;", engine)
    display(df)
    return df.tableName.to_list()


def select_from_table(
    database_name="default",
    table_name="transactions",
    host="dbt-spark3-thrift",
    port=10000,
    message_to_be_printed="",
    suffix_sql="",
):
    # sqlAlchemy api fail here due to "sqlAlchemy relection": TODO investigate root cause
    # engine = create_engine(f'hive://{spark_thrift_service_name}:10000/default')
    # df = pd.read_sql(f"select * from {table_name} limit 10", engine)

    print(message_to_be_printed)
    with hive.Connection(host=host, port=port, database=database_name) as conn:
        df = pd.read_sql(
            f"select * from {database_name}.{table_name} {suffix_sql};", conn
        )
        display(df)
        pass


# print(show_databases(message_to_be_printed="tables in database"))

table_names = show_tables(database_name="default", message_to_be_printed=f"{'='*10}")
# print("------------")
# select_from_table()
for names in table_names:
    select_from_table(
        table_name="raw__transactions", message_to_be_printed=f"{'-'*10}{names}"
    )

==========

  namespace          tableName  isTemporary
0   default  raw__transactions        False

----------raw__transactions

/tmp/ipykernel_11361/3788726696.py:59: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(

   id   amount currency    status
0   1  100.000      USD    ACTIVE
1   3  150.020      EUR    ACTIVE
2   5  180.040      SGD  INACTIVE
3   6 -300.050      JPY    ACTIVE
4   2  200.010      SGD    ACTIVE
5   4  120.030      USD  INACTIVE
6   7  300.123      SUD    ACTIVE

## DBT

In [283]:
!dbt --version

25507.86s - pydevd: Sending message related to process being replaced timed-out after 5 seconds

Core:
  - installed: 1.10.2
  - latest:    1.10.4 - Update available!

  Your version of dbt-core is out of date!
  You can find instructions for upgrading here:
  https://docs.getdbt.com/docs/installation

Plugins:
  - spark: 1.9.2 - Up to date!

## Verify DBT setup

### profiles.yml
```yml
formal_verification_prj_name:
  outputs:
    spark:
      type: spark
      method: thrift
      host: dbt-spark3-thrift
      schema: default
      connect_timeout: 30
      authentication: NONE
  target: spark

```

In [12]:
!cat $dbt_project_dir/dbt_project.yml | grep -v "#"

name: 'dbt_spark_demo_prj'
version: '1.0.0'

profile: 'dbt_spark_demo_prj'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

  - "target"
  - "dbt_packages"



models:
  dbt_spark_demo_prj:
    +materialized: incremental
    +file_format: parquet

tests:

### dbt debug

In [14]:
!dbt debug --project-dir $dbt_project_dir;

#to print detailed messages for debugging 
#!dbt debug --debug --project-dir /usr/app/dbt/dbt_spark_demo_prj

00:57:19  Running with dbt=1.10.2
00:57:19  dbt version: 1.10.2
00:57:19  python version: 3.11.2
00:57:19  python path: /usr/local/bin/python3
00:57:19  os info: Linux-5.15.167.4-microsoft-standard-WSL2-x86_64-with-glibc2.31
00:57:19  Using profiles dir at /root/.dbt
00:57:19  Using profiles.yml file at /root/.dbt/profiles.yml
00:57:19  Using dbt_project.yml file at /usr/app/dbt/dbt_spark_demo_prj/dbt_project.yml
00:57:19  adapter type: spark
00:57:19  adapter version: 1.9.2
00:57:19  Configuration:
00:57:19    profiles.yml file [OK found and valid]
00:57:19    dbt_project.yml file [OK found and valid]
00:57:19  Required dependencies:
00:57:19   - git [OK found]

00:57:19  Connection:
00:57:19    host: dbt-spark3-thrift
00:57:19    port: 10000
00:57:19    cluster: None
00:57:19    endpoint: None
00:57:19    schema: default
00:57:19    organization: 0
00:57:19  Registered adapter: spark=1.9.2
00:57:19    Connection test: [OK connection ok]

00:57:19  All checks passed!

## dbt command comparisons
| Command           | Purpose                                  | What it does                                                             | Output                                    |
| ----------------- | ---------------------------------------- | ------------------------------------------------------------------------ | ----------------------------------------- |
| **`dbt compile`** | Prepares SQL code for execution          | Converts Jinja + macros into raw SQL; writes compiled files to `target/` | Compiled SQL files (no warehouse changes) |
| **`dbt run`**     | Builds models (tables/views)             | Executes compiled SQL to materialize models in the data warehouse        | Tables/views in the warehouse             |
| **`dbt test`**    | Validates data quality assumptions       | Runs data tests (e.g., `not_null`, `unique`, custom) on warehouse data   | Test pass/fail results                    |
| **`dbt seed`**    | Loads static CSV data into the warehouse | Uploads CSV files from the `seeds/` directory into tables                 | Tables containing seed data               |

# Delete database table

In [ ]:
db_names = show_databases()
print(db_names)
for d in db_names:
    if d != 'default':
        arg = "'{" + '"database_name"' + ": " + f'"{d}"' + "}'"
        print(f"arg {arg}")
        !dbt run-operation drop_database --args $arg  
database_names = show_databases();

table_names = show_tables(database_name="default",  message_to_be_printed="Tables in default database before deleting table");
for t in table_names:
    print(t)
    arg = "'{" + '"table_name"' + ":" + f'"default.{t}"' + "}'"
    !dbt run-operation drop_table --args $arg  
table_names = show_tables(database_name="default", message_to_be_printed="Tables in default database after deleting table");

                 namespace
0                  default
1  default_dbt_test__audit

['default', 'default_dbt_test__audit']
arg '{"database_name": "default_dbt_test__audit"}'
02:04:20  Running with dbt=1.10.2
02:04:20  Registered adapter: spark=1.9.2
02:04:21  Found 1 model, 1 seed, 8 data tests, 478 macros, 3 unit tests

  namespace
0   default

Empty DataFrame
Columns: [namespace, tableName, isTemporary]
Index: []

Empty DataFrame
Columns: [namespace, tableName, isTemporary]
Index: []

# Generate SQL for models and seeds

## Read input csv 

* read seeds/transactions.csv, 
* dbt generate raw__transaction.csv
* dbt create table default.raw_transaction at the database

In [25]:
!dbt seed --project-dir $dbt_project_dir;
show_databases(message_to_be_printed="\nDatabase table after the operation")
show_tables(message_to_be_printed="\nTable after the dbt seed")
select_from_table(
    database_name="default", table_name="raw__transactions", suffix_sql="order by id"
)

01:11:08  Running with dbt=1.10.2
01:11:09  Registered adapter: spark=1.9.2
01:11:10  Found 1 seed, 8 data tests, 1 model, 479 macros, 3 unit tests
01:11:10
01:11:10  Concurrency: 1 threads (target='spark')
01:11:10
01:11:11  1 of 1 START seed file default.raw__transactions ............................... [RUN]
01:11:12  1 of 1 OK loaded seed file default.raw__transactions ........................... [INSERT 7 in 1.71s]
01:11:12
01:11:12  Finished running 1 seed in 0 hours 0 minutes and 2.32 seconds (2.32s).
01:11:13
01:11:13  Completed successfully
01:11:13
01:11:13  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 NO-OP=0 TOTAL=1

Database table after the operation

  namespace
0   default

Table after the dbt seed

  namespace          tableName  isTemporary
0   default  raw__transactions        False

/tmp/ipykernel_11361/3788726696.py:59: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(

   id   amount currency    status
0   1  100.000      USD    ACTIVE
1   2  200.010      SGD    ACTIVE
2   3  150.020      EUR    ACTIVE
3   4  120.030      USD  INACTIVE
4   5  180.040      SGD  INACTIVE
5   6 -300.050      JPY    ACTIVE
6   7  300.123      SUD    ACTIVE

# Generate SQL (dbt compile)

In [30]:
!rm -rf $dbt_project_dir/target/compiled/
!dbt compile --project-dir $dbt_project_dir --log-level debug;
# !export TZ='Asia/Singapore'; date; ls -lrt dbt/dbt_spark_demo_prj/target/compiled/

01:33:43  Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f7fc3aa7c10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f7fc4a2d410>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f7fc491b050>]}
01:33:43  Running with dbt=1.10.2
01:33:43  running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/root/.dbt', 'version_check': 'True', 'fail_fast': 'False', 'log_path': '/usr/app/dbt/dbt_spark_demo_prj/logs', 'debug': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'invocation_command': 'dbt compile --project-dir /usr/app/dbt/dbt_spark_demo_prj --log-level debug', 'static_parser': 'True', 'introspect': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
01:33:43  Spark adapter: Setting pyhive.hive logging to ERROR
01:33:43  Spark adapter: Setting thrift.transport logging to ERROR
01:33:43  Spark adapter: Setting thrift.protocol logging to ERROR
01:33:44  Sending event: {'category': 'dbt', 'action': 'project_id', 'label': '4ced1107-37ca-49a4-bd8b-98242d8e29a6', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f7fc39421d0>]}
01:33:44  Sending event: {'category': 'dbt', 'action': 'adapter_info', 'label': '4ced1107-37ca-49a4-bd8b-98242d8e29a6', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f7fc3d5e8d0>]}
01:33:44  Registered adapter: spark=1.9.2
01:33:44  checksum: 1adc40777973ef30f45f80b3b6d04d5013c1edd53d96363881b3b199e612468b, vars: {}, profile: , target: , version: 1.10.2
01:33:44  Partial parsing enabled: 0 files deleted, 0 files added, 0 files changed.
01:33:44  Partial parsing enabled, no changes found, skipping parsing
01:33:45  Sending event: {'category': 'dbt', 'action': 'load_project', 'label': '4ced1107-37ca-49a4-bd8b-98242d8e29a6', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f7fc3affe90>]}
01:33:45  Wrote artifact WritableManifest to /usr/app/dbt/dbt_spark_demo_prj/target/manifest.json
01:33:45  Wrote artifact SemanticManifest to /usr/app/dbt/dbt_spark_demo_prj/target/semantic_manifest.json
01:33:45  Sending event: {'category': 'dbt', 'action': 'resource_counts', 'label': '4ced1107-37ca-49a4-bd8b-98242d8e29a6', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f7fc3b20550>]}
01:33:45  Found 1 seed, 8 data tests, 1 model, 477 macros, 3 unit tests
01:33:45  Sending event: {'category': 'dbt', 'action': 'runnable_timing', 'label': '4ced1107-37ca-49a4-bd8b-98242d8e29a6', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f7fc2f73210>]}
01:33:45
01:33:45  Concurrency: 1 threads (target='spark')
01:33:45
01:33:45  Acquiring new spark connection 'master'
01:33:45  Acquiring new spark connection 'list_None_default_dbt_test__audit'
01:33:45  Spark adapter: NotImplemented: add_begin_query
01:33:45  Using spark connection "list_None_default_dbt_test__audit"
01:33:45  On list_None_default_dbt_test__audit: /* {"app": "dbt", "dbt_version": "1.10.2", "profile_name": "dbt_spark_demo_prj", "target_name": "spark", "connection_name": "list_None_default_dbt_test__audit"} */
show table extended in default_dbt_test__audit like '*'

01:33:45  Opening a new connection, currently in state init
01:33:46  Spark adapter: Poll status: 2, query complete
01:33:46  SQL status: OK in 0.575 seconds
01:33:46  On list_None_default_dbt_test__audit: ROLLBACK
01:33:46  Spark adapter: NotImplemented: rollback
01:33:46  On list_None_default_dbt_test__audit: Close
01:33:46  Re-using an available connection from the pool (formerly list_None_default_dbt_test__audit, now list_None_default)
01:33:46  Spark adapter: NotImplemented: add_begin_query
01:33:46  Using spark connection "list_None_default"
01:33:46  On list_None_default: /* {"app": "dbt", "dbt_version": "1.10.2", "profile_name": "dbt_spark_demo_prj", "target_name": "spark", "connection_name": "list_None_default"} */
show table extended in default like '*'

01:33:46  Opening a new connection, currently in state closed
01:33:46  Spark adapter: Poll status: 2, query complete
01:33:46  SQL status: OK in 0.195 seconds
01:33:46  On list_None_default: ROLLBACK
01:33:46  Spark adapter: NotImplemented: rollback
01:33:46  On list_None_default: Close
01:33:46  Sending event: {'category': 'dbt', 'action': 'runnable_timing', 'label': '4ced1107-37ca-49a4-bd8b-98242d8e29a6', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f7fc38f1a90>]}
01:33:46  Began running node seed.dbt_spark_demo_prj.raw__transactions
01:33:46  Re-using an available connection from the pool (formerly list_None_default, now seed.dbt_spark_demo_prj.raw__transactions)
01:33:46  Began compiling node seed.dbt_spark_demo_prj.raw__transactions
01:33:46  Began executing node seed.dbt_spark_demo_prj.raw__transactions
01:33:46  Finished running node seed.dbt_spark_demo_prj.raw__transactions
01:33:46  Began running node model.dbt_spark_demo_prj.transactions
01:33:46  Re-using an available connection from the pool (formerly seed.dbt_spark_demo_prj.raw__transactions, now model.dbt_spark_demo_prj.transactions)
01:33:46  Began compiling node model.dbt_spark_demo_prj.transactions
01:33:46  Writing injected SQL for node "model.dbt_spark_demo_prj.transactions"
01:33:46  Began executing node model.dbt_spark_demo_prj.transactions
01:33:46  Finished running node model.dbt_spark_demo_prj.transactions
01:33:46  Began running node test.dbt_spark_demo_prj.all_columns_non_null_in_seeds_raw__transactions_.d8ebeb41b5
01:33:46  Re-using an available connection from the pool (formerly model.dbt_spark_demo_prj.transactions, now test.dbt_spark_demo_prj.all_columns_non_null_in_seeds_raw__transactions_.d8ebeb41b5)
01:33:46  Began compiling node test.dbt_spark_demo_prj.all_columns_non_null_in_seeds_raw__transactions_.d8ebeb41b5
01:33:46  Spark adapter: NotImplemented: add_begin_query
01:33:46  Using spark connection "test.dbt_spark_demo_prj.all_columns_non_null_in_seeds_raw__transactions_.d8ebeb41b5"
01:33:46  On test.dbt_spark_demo_prj.all_columns_non_null_in_seeds_raw__transactions_.d8ebeb41b5: /* {"app": "dbt", "dbt_version": "1.10.2", "profile_name": "dbt_spark_demo_prj", "target_name": "spark", "node_id": "test.dbt_spark_demo_prj.all_columns_non_null_in_seeds_raw__transactions_.d8ebeb41b5"} */

      describe extended default.raw__transactions

01:33:46  Opening a new connection, currently in state closed
01:33:46  Spark adapter: Poll status: 2, query complete
01:33:46  SQL status: OK in 0.208 seconds
01:33:46  Writing injected SQL for node "test.dbt_spark_demo_prj.all_columns_non_null_in_seeds_raw__transactions_.d8ebeb41b5"
01:33:46  Began executing node test.dbt_spark_demo_prj.all_columns_non_null_in_seeds_raw__transactions_.d8ebeb41b5
01:33:46  On test.dbt_spark_demo_prj.all_columns_non_null_in_seeds_raw__transactions_.d8ebeb41b5: ROLLBACK
01:33:46  Spark adapter: NotImplemented: rollback
01:33:46  On test.dbt_spark_demo_prj.all_columns_non_null_in_seeds_raw__transactions_.d8ebeb41b5: Close
01:33:46  Finished running node test.dbt_spark_demo_prj.all_columns_non_null_in_seeds_raw__transactions_.d8ebeb41b5
01:33:46  Began running node test.dbt_spark_demo_prj.accepted_values_transactions_branch_marker__USD_BRANCH__SGD_BRANCH__UNKNOWN_BRANCH.a8c2f665b8
01:33:46  Re-using an available connection from the pool (formerly test.dbt_spark_demo_prj.all_columns_non_null_in_seeds_raw__transactions_.d8ebeb41b5, now test.dbt_spark_demo_prj.accepted_values_transactions_branch_marker__USD_BRANCH__SGD_BRANCH__UNKNOWN_BRANCH.a8c2f665b8)
01:33:46  Began compiling node test.dbt_spark_demo_prj.accepted_values_transactions_branch_marker__USD_BRANCH__SGD_BRANCH__UNKNOWN_BRANCH.a8c2f665b8
01:33:47  Writing injected SQL for node "test.dbt_spark_demo_prj.accepted_values_transactions_branch_marker__USD_BRANCH__SGD_BRANCH__UNKNOWN_BRANCH.a8c2f665b8"
01:33:47  Began executing node test.dbt_spark_demo_prj.accepted_values_transactions_branch_marker__USD_BRANCH__SGD_BRANCH__UNKNOWN_BRANCH.a8c2f665b8
01:33:47  Finished running node test.dbt_spark_demo_prj.accepted_values_transactions_branch_marker__USD_BRANCH__SGD_BRANCH__UNKNOWN_BRANCH.a8c2f665b8
01:33:47  Began running node test.dbt_spark_demo_prj.accepted_values_transactions_currency__USD__SGD.8f4f1136ea
01:33:47  Re-using an available connection from the pool (formerly test.dbt_spark_demo_prj.accepted_values_transactions_branch_marker__USD_BRANCH__SGD_BRANCH__UNKNOWN_BRANCH.a8c2f665b8, now test.dbt_spark_demo_prj.accepted_values_transactions_currency__USD__SGD.8f4f1136ea)
01:33:47  Began compiling node test.dbt_spark_demo_prj.accepted_values_transactions_currency__USD__SGD.8f4f1136ea
01:33:47  Writing injected SQL for node "test.dbt_spark_demo_prj.accepted_values_transactions_currency__USD__SGD.8f4f1136ea"
01:33:47  Began executing node test.dbt_spark_demo_prj.accepted_values_transactions_currency__USD__SGD.8f4f1136ea
01:33:47  Finished running node test.dbt_spark_demo_prj.accepted_values_transactions_currency__USD__SGD.8f4f1136ea
01:33:47  Began running node test.dbt_spark_demo_prj.all_columns_non_null_in_seeds_transactions_.ec8b98f60a
01:33:47  Re-using an available connection from the pool (formerly test.dbt_spark_demo_prj.accepted_values_transactions_currency__USD__SGD.8f4f1136ea, now test.dbt_spark_demo_prj.all_columns_non_null_in_seeds_transactions_.ec8b98f60a)
01:33:47  Began compiling node test.dbt_spark_demo_prj.all_columns_non_null_in_seeds_transactions_.ec8b98f60a
01:33:47  Spark adapter: NotImplemented: add_begin_query
01:33:47  Using spark connection "test.dbt_spark_demo_prj.all_columns_non_null_in_seeds_transactions_.ec8b98f60a"
01:33:47  On test.dbt_spark_demo_prj.all_columns_non_null_in_seeds_transactions_.ec8b98f60a: /* {"app": "dbt", "dbt_version": "1.10.2", "profile_name": "dbt_spark_demo_prj", "target_name": "spark", "node_id": "test.dbt_spark_demo_prj.all_columns_non_null_in_seeds_transactions_.ec8b98f60a"} */

      describe extended default.transactions

01:33:47  Opening a new connection, currently in state closed
01:33:47  Spark adapter: Poll status: 2, query complete
01:33:47  SQL status: OK in 0.236 seconds
01:33:47  Writing injected SQL for node "test.dbt_spark_demo_prj.all_columns_non_null_in_seeds_transactions_.ec8b98f60a"
01:33:47  Began executing node test.dbt_spark_demo_prj.all_columns_non_null_in_seeds_transactions_.ec8b98f60a
01:33:47  On test.dbt_spark_demo_prj.all_columns_non_null_in_seeds_transactions_.ec8b98f60a: ROLLBACK
01:33:47  Spark adapter: NotImplemented: rollback
01:33:47  On test.dbt_spark_demo_prj.all_columns_non_null_in_seeds_transactions_.ec8b98f60a: Close
01:33:47  Finished running node test.dbt_spark_demo_prj.all_columns_non_null_in_seeds_transactions_.ec8b98f60a
01:33:47  Began running node test.dbt_spark_demo_prj.not_null_transactions_branch_marker.a2b3b16bed
01:33:47  Re-using an available connection from the pool (formerly test.dbt_spark_demo_prj.all_columns_non_null_in_seeds_transactions_.ec8b98f60a, now test.dbt_spark_demo_prj.not_null_transactions_branch_marker.a2b3b16bed)
01:33:47  Began compiling node test.dbt_spark_demo_prj.not_null_transactions_branch_marker.a2b3b16bed
01:33:47  Writing injected SQL for node "test.dbt_spark_demo_prj.not_null_transactions_branch_marker.a2b3b16bed"
01:33:47  Began executing node test.dbt_spark_demo_prj.not_null_transactions_branch_marker.a2b3b16bed
01:33:47  Finished running node test.dbt_spark_demo_prj.not_null_transactions_branch_marker.a2b3b16bed
01:33:47  Began running node test.dbt_spark_demo_prj.not_null_transactions_currency.5becce707f
01:33:47  Re-using an available connection from the pool (formerly test.dbt_spark_demo_prj.not_null_transactions_branch_marker.a2b3b16bed, now test.dbt_spark_demo_prj.not_null_transactions_currency.5becce707f)
01:33:47  Began compiling node test.dbt_spark_demo_prj.not_null_transactions_currency.5becce707f
01:33:47  Writing injected SQL for node "test.dbt_spark_demo_prj.not_null_transactions_currency.5becce707f"
01:33:47  Began executing node test.dbt_spark_demo_prj.not_null_transactions_currency.5becce707f
01:33:47  Finished running node test.dbt_spark_demo_prj.not_null_transactions_currency.5becce707f
01:33:47  Began running node test.dbt_spark_demo_prj.not_null_transactions_id.6462b524d8
01:33:47  Re-using an available connection from the pool (formerly test.dbt_spark_demo_prj.not_null_transactions_currency.5becce707f, now test.dbt_spark_demo_prj.not_null_transactions_id.6462b524d8)
01:33:47  Began compiling node test.dbt_spark_demo_prj.not_null_transactions_id.6462b524d8
01:33:47  Writing injected SQL for node "test.dbt_spark_demo_prj.not_null_transactions_id.6462b524d8"
01:33:47  Began executing node test.dbt_spark_demo_prj.not_null_transactions_id.6462b524d8
01:33:47  Finished running node test.dbt_spark_demo_prj.not_null_transactions_id.6462b524d8
01:33:47  Began running node test.dbt_spark_demo_prj.unique_transactions_id.684003eda7
01:33:47  Re-using an available connection from the pool (formerly test.dbt_spark_demo_prj.not_null_transactions_id.6462b524d8, now test.dbt_spark_demo_prj.unique_transactions_id.684003eda7)
01:33:47  Began compiling node test.dbt_spark_demo_prj.unique_transactions_id.684003eda7
01:33:47  Writing injected SQL for node "test.dbt_spark_demo_prj.unique_transactions_id.684003eda7"
01:33:47  Began executing node test.dbt_spark_demo_prj.unique_transactions_id.684003eda7
01:33:47  Finished running node test.dbt_spark_demo_prj.unique_transactions_id.684003eda7
01:33:47  Connection 'master' was properly closed.
01:33:47  Connection 'test.dbt_spark_demo_prj.unique_transactions_id.684003eda7' was properly closed.
01:33:47  Command end result
01:33:47  Wrote artifact WritableManifest to /usr/app/dbt/dbt_spark_demo_prj/target/manifest.json
01:33:47  Wrote artifact SemanticManifest to /usr/app/dbt/dbt_spark_demo_prj/target/semantic_manifest.json
01:33:47  Wrote artifact RunExecutionResult to /usr/app/dbt/dbt_spark_demo_prj/target/run_results.json
01:33:47  Resource report: {"command_name": "compile", "command_success": true, "command_wall_clock_time": 4.2177625, "process_in_blocks": "0", "process_kernel_time": 0.798576, "process_mem_max_rss": "117424", "process_out_blocks": "2152", "process_user_time": 5.759732}
01:33:47  Command `dbt compile` succeeded at 01:33:47.646291 after 4.22 seconds
01:33:47  Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f7fc3aff550>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f7fc7e8a310>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f7fc7e8b150>]}
01:33:47  Flushing usage events
01:33:49  An error was encountered while trying to flush usage events

## Create tables using the generated SQL (dbt run)

In [31]:
# Delete database table prior dbt run that will create the table
!rm -r $dbt_project_dir/target/run
!dbt run-operation drop_table --args '{"table_name": "default.transactions"}' 

show_tables(database_name='default', message_to_be_printed="before")
!dbt run --log-level info --project-dir $dbt_project_dir;

# Check output dbt run
show_tables(database_name='default', message_to_be_printed="after")
select_from_table(database_name='default', table_name='transactions')

01:51:03  Running with dbt=1.10.2
01:51:03  Registered adapter: spark=1.9.2
01:51:04  Found 1 seed, 8 data tests, 1 model, 477 macros, 3 unit tests
before

  namespace          tableName  isTemporary
0   default  raw__transactions        False

01:51:11  Running with dbt=1.10.2
01:51:12  Registered adapter: spark=1.9.2
01:51:14  Found 1 seed, 8 data tests, 1 model, 477 macros, 3 unit tests
01:51:14
01:51:14  Concurrency: 1 threads (target='spark')
01:51:14
01:51:16  1 of 1 START sql table model default.transactions .............................. [RUN]
01:51:18  1 of 1 OK created sql table model default.transactions ......................... [OK in 1.71s]
01:51:18
01:51:18  Finished running 1 table model in 0 hours 0 minutes and 3.81 seconds (3.81s).
01:51:18
01:51:18  Completed successfully
01:51:18
01:51:18  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 NO-OP=0 TOTAL=1
after

  namespace          tableName  isTemporary
0   default  raw__transactions        False
1   default       transactions        False

/tmp/ipykernel_11361/3788726696.py:59: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(

   id   amount currency  amount_usd   branch_marker
0   1  100.000      USD    100.0000      USD_BRANCH
1   2  200.010      SGD    148.0074      SGD_BRANCH
2   6 -300.050      JPY         NaN  UNKNOWN_BRANCH
3   3  150.020      EUR         NaN  UNKNOWN_BRANCH
4   7  300.123      SUD         NaN  UNKNOWN_BRANCH

## Test model using dbt

#### test name and its test vectors

In [331]:
!tree $dbt_project_dir/tests
!cat $dbt_project_dir/models/transactions/schema.yml | grep -v "#"

39624.28s - pydevd: Sending message related to process being replaced timed-out after 5 seconds

/usr/app/dbt/dbt_spark_demo_prj/tests
├── schema
└── unit
    └── test_transactions.yml

2 directories, 1 file

39629.95s - pydevd: Sending message related to process being replaced timed-out after 5 seconds

version: 2

models:
  - name: transactions
    description: "Transactions data model."
    tests:
      - all_columns_non_null_in_seeds: {}

In [32]:
# %%bash
# export DBT_PROJECT_DIR=$dbt_project_dir
show_databases(message_to_be_printed="Before run test")
!dbt test --store-failures --project-dir $dbt_project_dir --log-level info;

Before run test

                 namespace
0                  default
1  default_dbt_test__audit

01:51:43  Running with dbt=1.10.2
01:51:44  Registered adapter: spark=1.9.2
01:51:44  Found 1 seed, 8 data tests, 1 model, 477 macros, 3 unit tests
01:51:44
01:51:44  Concurrency: 1 threads (target='spark')
01:51:44
01:51:45  1 of 11 START test accepted_values_transactions_branch_marker__USD_BRANCH__SGD_BRANCH__UNKNOWN_BRANCH  [RUN]
01:51:46  1 of 11 PASS accepted_values_transactions_branch_marker__USD_BRANCH__SGD_BRANCH__UNKNOWN_BRANCH  [PASS in 1.47s]
01:51:46  2 of 11 START test accepted_values_transactions_currency__USD__SGD ............. [RUN]
01:51:48  2 of 11 FAIL 3 accepted_values_transactions_currency__USD__SGD ................. [FAIL 3 in 1.14s]
01:51:48  3 of 11 START test all_columns_non_null_in_seeds_raw__transactions_ ............ [RUN]
01:51:49  3 of 11 PASS all_columns_non_null_in_seeds_raw__transactions_ .................. [PASS in 1.44s]
01:51:49  4 of 11 START test all_columns_non_null_in_seeds_transactions_ ................. [RUN]
01:51:51  4 of 11 FAIL 3 all_columns_non_null_in_seeds_transactions_ ..................... [FAIL 3 in 1.90s]
01:51:51  5 of 11 START test not_null_transactions_branch_marker ......................... [RUN]
01:51:53  5 of 11 PASS not_null_transactions_branch_marker ............................... [PASS in 2.07s]
01:51:53  6 of 11 START test not_null_transactions_currency .............................. [RUN]
01:51:55  6 of 11 PASS not_null_transactions_currency .................................... [PASS in 1.84s]
01:51:55  7 of 11 START test not_null_transactions_id .................................... [RUN]
01:51:56  7 of 11 PASS not_null_transactions_id .......................................... [PASS in 1.57s]
01:51:56  8 of 11 START test unique_transactions_id ...................................... [RUN]
01:51:58  8 of 11 PASS unique_transactions_id ............................................ [PASS in 1.11s]
01:51:58  9 of 11 START unit_test transactions::test_currency_sgd ........................ [RUN]
01:51:58  9 of 11 FAIL 1 transactions::test_currency_sgd ................................. [FAIL 1 in 0.59s]
01:51:58  10 of 11 START unit_test transactions::test_currency_usd ....................... [RUN]
01:51:59  10 of 11 PASS transactions::test_currency_usd .................................. [PASS in 0.35s]
01:51:59  11 of 11 START unit_test transactions::test_inactive ........................... [RUN]
01:51:59  11 of 11 PASS transactions::test_inactive ...................................... [PASS in 0.45s]
01:51:59
01:51:59  Finished running 8 data tests, 3 unit tests in 0 hours 0 minutes and 14.62 seconds (14.62s).
01:51:59
01:51:59  Completed with 3 errors, 0 partial successes, and 0 warnings:
01:51:59
01:51:59  Failure in test accepted_values_transactions_currency__USD__SGD (models/transactions/transactions.yml)
01:51:59    Got 3 results, configured to fail if != 0
01:51:59
01:51:59    compiled code at target/compiled/dbt_spark_demo_prj/models/transactions/transactions.yml/accepted_values_transactions_currency__USD__SGD.sql
01:51:59
01:51:59    See test failures:
  -------------------------------------------------------------------------------------
  select * from default_dbt_test__audit.accepted_values_transactions_currency__USD__SGD
  -------------------------------------------------------------------------------------
01:51:59
01:51:59  Failure in test all_columns_non_null_in_seeds_transactions_ (models/transactions/transactions.yml)
01:51:59    Got 3 results, configured to fail if != 0
01:51:59
01:51:59    compiled code at target/compiled/dbt_spark_demo_prj/models/transactions/transactions.yml/all_columns_non_null_in_seeds_transactions_.sql
01:51:59
01:51:59    See test failures:
  ---------------------------------------------------------------------------------
  select * from default_dbt_test__audit.all_columns_non_null_in_seeds_transactions_
  ---------------------------------------------------------------------------------
01:51:59
01:51:59  Failure in unit_test test_currency_sgd (tests/unit/test_transactions.yml)
01:51:59

actual differs from expected:

@@,id,amount_usd,branch_marker
→ ,2 ,74.0→NULL ,SGD_BRANCH→UNKNOWN_BRANCH


01:51:59
01:51:59    compiled code at target/compiled/dbt_spark_demo_prj/tests/unit/test_transactions.yml/tests/unit/test_currency_sgd.sql
01:51:59
01:51:59  Done. PASS=8 WARN=0 ERROR=3 SKIP=0 NO-OP=0 TOTAL=11

In [33]:
database_names = show_databases(message_to_be_printed="After run test")
for d in database_names:
    if d != "default" and "audit" in d:
        table_names = show_tables(
            message_to_be_printed=f"database_name: {d}", database_name=d
        )
        for t in table_names:
            select_from_table(
                table_name=t,
                database_name=d,
                message_to_be_printed=f"\t\ttable_name: {t}",
            )

After run test

                 namespace
0                  default
1  default_dbt_test__audit

database_name: default_dbt_test__audit

,namespace,tableName,isTemporary
0,default_dbt_test__audit,accepted_values_transactions_4f8a22968ef4aeace...,False
1,default_dbt_test__audit,accepted_values_transactions_currency__usd__sgd,False
2,default_dbt_test__audit,all_columns_non_null_in_seeds_raw__transactions_,False
3,default_dbt_test__audit,all_columns_non_null_in_seeds_transactions_,False
4,default_dbt_test__audit,not_null_transactions_branch_marker,False
5,default_dbt_test__audit,not_null_transactions_currency,False
6,default_dbt_test__audit,not_null_transactions_id,False
7,default_dbt_test__audit,unique_transactions_id,False

		table_name: accepted_values_transactions_4f8a22968ef4aeace3943278926b5107

/tmp/ipykernel_11361/3788726696.py:59: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(

Empty DataFrame
Columns: [value_field, n_records]
Index: []

		table_name: accepted_values_transactions_currency__usd__sgd

/tmp/ipykernel_11361/3788726696.py:59: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(

  value_field  n_records
0         JPY          1
1         EUR          1
2         SUD          1

		table_name: all_columns_non_null_in_seeds_raw__transactions_

/tmp/ipykernel_11361/3788726696.py:59: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(

Empty DataFrame
Columns: [CASE WHEN (id IS NULL) THEN id ELSE NULL END, CASE WHEN (amount IS NULL) THEN amount ELSE NULL END, CASE WHEN (currency IS NULL) THEN currency ELSE NULL END, CASE WHEN (status IS NULL) THEN status ELSE NULL END]
Index: []

		table_name: all_columns_non_null_in_seeds_transactions_

/tmp/ipykernel_11361/3788726696.py:59: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(

,CASE WHEN (id IS NULL) THEN id ELSE NULL END,CASE WHEN (amount IS NULL) THEN amount ELSE NULL END,CASE WHEN (currency IS NULL) THEN currency ELSE NULL END,CASE WHEN (amount_usd IS NULL) THEN amount_usd ELSE NULL END,CASE WHEN (branch_marker IS NULL) THEN branch_marker ELSE NULL END
0,None,None,None,amount_usd,None
1,None,None,None,amount_usd,None
2,None,None,None,amount_usd,None

		table_name: not_null_transactions_branch_marker

/tmp/ipykernel_11361/3788726696.py:59: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(

Empty DataFrame
Columns: [id, amount, currency, amount_usd, branch_marker]
Index: []

		table_name: not_null_transactions_currency

/tmp/ipykernel_11361/3788726696.py:59: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(

Empty DataFrame
Columns: [id, amount, currency, amount_usd, branch_marker]
Index: []

		table_name: not_null_transactions_id

/tmp/ipykernel_11361/3788726696.py:59: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(

Empty DataFrame
Columns: [id, amount, currency, amount_usd, branch_marker]
Index: []

		table_name: unique_transactions_id

/tmp/ipykernel_11361/3788726696.py:59: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(

Empty DataFrame
Columns: [unique_field, n_records]
Index: []

In [ ]:
!chmod -R a+rw /usr/app

In [ ]:
filepath="/usr/app/demo/results/test_end.txt"
!date; echo end test at > $filepath 
!export TZ='Asia/Singapore'; date >> $filepath;

In [ ]:
# assert False, "Stop execution here!"

# Apendix

## check the model built

### Check the model built using Pyspark (In progress)

In [ ]:
# !pip install pyspark==3.3.2

In [ ]:
# %%bash
# # For Debian/Ubuntu-based containers:
# apt-get update && apt-get install -y openjdk-11-jdk

# # For Alpine-based containers:
# apk add openjdk11

In [ ]:
# !ls /usr/lib/jvm/java-11-openjdk-amd64

In [ ]:
# # !. /usr/spark/bin/load-spark-env.sh

# # Typically in Debian/Ubuntu:
# !export JAVA_HOME=$(dirname $(dirname $(readlink -f $(which java))))

# # Or set it explicitly:
# !export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
# from pyspark.sql import SparkSession

# spark = SparkSession.builder \
#     .appName("dbt_clean") \
#     .config("spark.hadoop.hive.metastore.schema.verification", "true") \
#     .config("spark.sql.catalogImplementation", "hive") \
#     .enableHiveSupport() \
#     .getOrCreate()

# # spark = SparkSession.builder \
# #     .config("hive.metastore.uris", "thrift://dbt-hive-metastore:10000") \
# #     .config("spark.sql.catalogImplementation", "hive") \
# #     .enableHiveSupport() \
# #     .getOrCreate()

# spark.sql("USE default")  # Or your specific database
# spark.sql("SHOW DATABASES").show()
# # spark.sql("select * from transactions").show()
# # # df.toPandas()

In [ ]:
# spark.sql("SHOW TABLES IN default").show(truncate=False)

In [ ]:
# # Query metastore system tables
# spark.sql("""
#   SELECT TBL_NAME, TBL_TYPE
#   FROM default.TBLS
#   JOIN default.DBS ON TBLS.DB_ID = DBS.DB_ID
#   WHERE DBS.NAME = 'default'
# """).show(truncate=False)

In [ ]:
# spark.conf.get("hive.metastore.uris")  # Should return your URI

In [ ]:
# spark.conf.get("spark.sql.catalogImplementation")  # Should return "hive"

In [ ]:
# from pyspark.sql import SparkSession

# spark.stop()
# spark = SparkSession.builder \
#     .appName("DBTIntegration") \
#     .config("hive.metastore.uris", "thrift://dbt-hive-metastore:9083") \
#     .config("spark.sql.catalogImplementation", "hive") \
#     .config("javax.jdo.option.ConnectionUserName", "dbt") \
#     .config("javax.jdo.option.ConnectionPassword", "dbt") \
#     .enableHiveSupport() \
#     .getOrCreate()
# spark.sql("SHOW TABLES IN default")

In [ ]:
# from pyhive import hive
# conn = hive.connect(host=spark_thrift_service_name, port=10000)
# cursor = conn.cursor()
# cursor.execute("SELECT * FROM default.transactions LIMIT 1")
# print(cursor.fetchall())

### Test the built model (using the test model) 
### dbt test

In [ ]:
# !dbt test --log-level info

In [ ]:
# !cat /home/vin/01-prj/stripe/sql-formal-verification/formal_verification_prj_name/tests/unit/test_transactions.yml

In [ ]:
# %%bash
# cd /usr/app/dbt
# dbt compile --profiles-dir /usr/app/dbt  --project-dir /usr/app/dbt/dbt_spark_demo_prj
# # dbt run-operation drop_table --args '{"table_name": "default.transactions"}'
# dbt run-operation drop_view --args '{"view_name": "default.my_first_dbt_model"}' --profiles-dir /usr/app/dbt  --project-dir /usr/app/dbt/dbt_spark_demo_prj
# dbt run-operation drop_view --args '{"view_name": "default.my_second_dbt_model"}' --profiles-dir /usr/app/dbt  --project-dir /usr/app/dbt/dbt_spark_demo_prj

<!-- # Todo
## Audit compliance 
### time tracing with time-stamping
1. Add timestamp for loaded data using dbt model
```jinja
SELECT
    *,
    '{{ run_started_at }}'::timestamp AS added_at
FROM {{ ref('my_seed_table') }}
```
### File tracing with source and targets file path, tablename -->

# End of notebook